# Generated by Django 3.0.6 on 2020-05-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualiCar_API', '0005_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qualiCar_API.Part'),
        ),
    ]
