# Generated by Django 3.0.6 on 2020-05-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualiCar_API', '0006_auto_20200527_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='part',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='qualiCar_API.Part'),
        ),
    ]
