# Generated by Django 3.0.6 on 2020-05-29 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qualiCar_API', '0008_auto_20200529_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 18, 2, 56, 645937, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_change_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 18, 2, 56, 645961, tzinfo=utc)),
        ),
    ]
