# Generated by Django 3.0.6 on 2020-05-29 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qualiCar_API', '0009_auto_20200529_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 18, 29, 59, 40665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='incident',
            name='last_change_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 18, 29, 59, 40690, tzinfo=utc)),
        ),
    ]
