# Generated by Django 3.0.6 on 2020-05-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualiCar_API', '0012_auto_20200529_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='last_change_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='part',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='qualiCar_API.Part'),
        ),
    ]
