# Generated by Django 3.0.6 on 2020-06-05 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualiCar_API', '0013_auto_20200529_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='part',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualiCar_API.Part'),
        ),
    ]
